version: 2
jobs:
  build:
    docker:
      - image: circleci/python:3.6.1

    working_directory: ~/mipt-ml-tasks

    steps:
      - checkout

      - restore_cache:
          keys:
          - v1-dependencies-{{ checksum "requirements.txt" }}
          - v1-dependencies-

      - run:
          name: install dependencies
          command: |
            python3 -m venv venv
            . venv/bin/activate
            pip install -r requirements.txt
            pip install kaggle
            mkdir ~/.kaggle
            echo $kaggle_api > ~/.kaggle/kaggle.json
      - save_cache:
          paths:
            - ./venv
          key: v1-dependencies-{{ checksum "requirements.txt" }}
        
      - run:
          name:
          command: |
            . venv/bin/activate
            kaggle competitions download titanic
            jupyter nbconvert --execute task2/eda-base-solution.ipynb
            kaggle competitions submit titanic -f submit.csv -m "submission_from_circle_ci"
